### PR TITLE
Add possibility to specify host in config and server elements

### PR DESCRIPTION
**Pull request by jphire**
- Add possibility to specify host ip for the server
- Useful/required for testing with VMs, because external connections are made
  between multiple guests

### CODE REVIEW

**Comment by jmineraud** [comment]
Hi, there is a basic .conf file you have to give as argument. A small set a
parameters are configurable there

**Comment by jphire** [comment]
Yes, but the hub's ip could not be changed from the config file without doing some modifications in the code (assumed '127.0.0.1'). The above changes add possibility to set host ip from configuration file, and still should be backwards compatible with the former version.

**Comment by jmineraud** [comment]
Can't you do address redirect from localhost:8001 to ip xxx.xxx.xxx.xxx
and localhost:8002 to ip xxx.xxx.xxx.yyy ?

2015-11-05 9:21 GMT+02:00 Janne Laukkanen notifications@github.com:

**Comment by jphire** [comment]
Of course, but that is not the problem. The problem is, that if you start the iothub server anywhere with '127.0.0.1' as it's bound address, it will not accept connections from outside. When you start the server bound to '0.0.0.0', it will bind to any address instead of just local ones. In testing this is not a problem, but in production etc. some source ip filtering could be reasonable. I guess I phrased the problem somewhat unclearly, because all I need is to be able to set the server's bound address to 0.0.0.0, so I don't need any ssh tricks to access the server from other hosts.

**Comment by jmineraud** [comment]
I have merge the branch to master

**Pull request merged**
